version: '3'
services:
  python-app:
    image: <nombre_imagen>
    build:
      context: .
    volumes:
      - .:/app  # Mapea tu carpeta de trabajo local al contenedor
    ports:
      - "5678:5678"  # El puerto para la depuración
    command: tail -f /dev/null  # Deja el contenedor en ejecución sin hacer nada
    stdin_open: true  # Permite la entrada estándar interactiva
    tty: true  # Mantiene la terminal interactiva