version: '3.8'

services:
  python-app:
    container_name: customimgsearch-python_dev # Nombre del contenedor
    image: customimgsearch-python_dev # Nombre de la imagen a construir
    build:
      context: . # Construcción desde el directorio actual

    environment:
      - PYTHONUNBUFFERED=1 # Evita buffering en logs de Python
      - PYTHONPATH=/app/src # Permite importar módulos desde `src`

    volumes:
      - .:/app:cached # Sincroniza código evitando problemas de rendimiento
      - ./src:/app/src
      - ./vscode-config:/root/.vscode-server # Monta configuración de VS Code en el contenedor

    ports:
      - "8080:8080" # Puerto para code-server (VS Code en el navegador)
      - "5678:5678" # Puerto para depuración remota con Debugpy u otros depuradores

    command: sleep infinity # Mantiene el contenedor activo sin consumir CPU

    stdin_open: true # Permite interacción con la terminal
    tty: true # Mantiene la terminal activa

    restart: unless-stopped # Reinicia automáticamente salvo que se detenga manualmente
